# Generated by Django 4.2.24 on 2025-09-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_supplierproduct_quoteitem_ownerquoteadjustment'),
        ('accounts', '0003_role_membership_role_fk'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplierproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.ticket'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status'], name='billing_ord_organiz_d7e065_idx'),
        ),
    ]
