# Generated by Django 4.2.24 on 2025-09-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_note',
            field=models.TextField(blank=True),
        ),
    ]
