# Generated by GitHub Copilot on 2025-09-07
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_membership_role_fk"),
        ("core", "0003_portal_user_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="accounts.organization")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="categories", to="core.supplier")),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="core.category")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="core.customer")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="accounts.organization")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
