# Generated by GitHub Copilot on 2025-09-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_category_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="supplier",
        ),
        migrations.AddField(
            model_name="category",
            name="suppliers",
            field=models.ManyToManyField(blank=True, related_name="categories", to="core.supplier"),
        ),
    ]
