# Generated by Django 4.2.24 on 2025-09-07 09:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticketattachment_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ticket',
            name='offered_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_tickets', to='core.quote'),
        ),
    ]
