# Generated by Django 4.2.24 on 2025-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_markup_amount_ticket_offered_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
