# Generated by Django 4.2.24 on 2025-09-07 14:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_membership_role_fk'),
        ('core', '0008_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='accounts.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.supplier')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='core.supplierproduct')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OwnerQuoteAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_adjustments', to='core.quoteitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_adjustments', to='core.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'quote_item'], name='core_ownerq_ticket__bfdd29_idx')],
                'unique_together': {('ticket', 'quote_item')},
            },
        ),
    ]
