# Generated by Django 4.2.24 on 2025-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supplierproduct_quoteitem_ownerquoteadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
    ]
