# Generated by Django 4.2.24 on 2025-09-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quote_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_comments', to='core.customer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.quote')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_comments', to='core.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='core_quotec_ticket__00dae2_idx')],
            },
        ),
    ]
