# Generated by Django 4.2.24 on 2025-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_categoryformfield_ticket_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryformfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
