# Generated by Django 4.2 on 2025-09-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_categoryformfield_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySupplierRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("min_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("max_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("field_name", models.CharField(blank=True, help_text="Category form field key (name)", max_length=100)),
                ("field_operator", models.CharField(blank=True, choices=[("eq", "="), ("neq", "!="), ("contains", "contains"), ("in", "in (comma separated)")], max_length=20)),
                ("field_value", models.CharField(blank=True, max_length=255)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="supplier_rules", to="core.category")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="category_supplier_rules", to="accounts.organization")),
            ],
            options={
                "ordering": ["category", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="categorysupplierrule",
            name="suppliers",
            field=models.ManyToManyField(blank=True, related_name="category_rules", to="core.supplier"),
        ),
    ]
