# Generated by Django 4.2.24 on 2025-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categorysupplierrule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('organization', 'email'), name='unique_customer_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('organization', 'email'), name='unique_supplier_email_per_org'),
        ),
    ]
