# Generated by Django 4.2.24 on 2025-11-10 09:21

from django.db import migrations, models


def migrate_organizations_forward(apps, schema_editor):
    """Copy existing organization FK relationships to new M2M field."""
    Supplier = apps.get_model('core', 'Supplier')
    for supplier in Supplier.objects.select_related('organization').all():
        if supplier.organization_id:
            supplier.organizations.add(supplier.organization)


def migrate_organizations_backward(apps, schema_editor):
    """Restore organization FK from M2M (take first organization)."""
    Supplier = apps.get_model('core', 'Supplier')
    for supplier in Supplier.objects.prefetch_related('organizations').all():
        first_org = supplier.organizations.first()
        if first_org:
            supplier.organization = first_org
            supplier.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_membership_role_fk'),
        ('core', '0017_add_category_hierarchy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_email_per_org',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='core_suppli_organiz_1eb51c_idx',
        ),
        # Add M2M field before removing FK so we can migrate data
        migrations.AddField(
            model_name='supplier',
            name='organizations',
            field=models.ManyToManyField(related_name='suppliers', to='accounts.organization', verbose_name='Organizasyonlar'),
        ),
        # Migrate existing data from FK to M2M
        migrations.RunPython(migrate_organizations_forward, migrate_organizations_backward),
        # Now remove the old FK field
        migrations.RemoveField(
            model_name='supplier',
            name='organization',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
