# Generated by Django 4.2.24 on 2025-11-11 05:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_unique_tokens(apps, schema_editor):
    """Generate unique UUID tokens for existing tickets."""
    Ticket = apps.get_model('core', 'Ticket')
    for ticket in Ticket.objects.all():
        ticket.supplier_token = uuid.uuid4()
        ticket.save(update_fields=['supplier_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_comparison_operators'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='ticket',
            name='supplier_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate unique values
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Step 3: Make it non-null and unique
        migrations.AlterField(
            model_name='ticket',
            name='supplier_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='TicketEmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_replies', to='core.supplier')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_replies', to='core.ticket')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
