# Generated by Django 4.2.24 on 2025-11-16 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_add_organization_email_settings"),
        ("core", "0026_add_metrics_and_scoring_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryformfield",
            name="field_type",
            field=models.CharField(
                choices=[("text", "Metin"), ("select", "Seçim (Dropdown)")],
                default="text",
                max_length=10,
                verbose_name="Alan Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="help_text",
            field=models.CharField(blank=True, max_length=200, verbose_name="Yardım Metni"),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Etiket"),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="name",
            field=models.SlugField(
                help_text="Veri anahtarı (otomatik üretilebilir)",
                max_length=100,
                verbose_name="Alan Adı",
            ),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="options",
            field=models.TextField(
                blank=True,
                help_text="Select için seçenekleri satır satır yazın",
                verbose_name="Seçenekler",
            ),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.AlterField(
            model_name="categoryformfield",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Zorunlu"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="field_name",
            field=models.CharField(
                blank=True,
                help_text="Kategori form alan anahtarı",
                max_length=100,
                verbose_name="Alan Adı",
            ),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="field_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eq", "="),
                    ("neq", "!="),
                    ("gt", ">"),
                    ("gte", ">="),
                    ("lt", "<"),
                    ("lte", "<="),
                    ("contains", "içerir"),
                    ("in", "şunlardan biri (virgülle ayırın)"),
                ],
                max_length=20,
                verbose_name="Operatör",
            ),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="field_value",
            field=models.CharField(blank=True, max_length=255, verbose_name="Değer"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="label",
            field=models.CharField(max_length=120, verbose_name="Etiket"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="max_quantity",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="En Çok Adet"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="min_quantity",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="En Az Adet"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.AlterField(
            model_name="categorysupplierrule",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="category_rules",
                to="core.supplier",
                verbose_name="Tedarikçiler",
            ),
        ),
        migrations.CreateModel(
            name="UserDashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("daily_orders", "Günlük Siparişler"),
                            ("weekly_orders", "Haftalık Siparişler"),
                            ("monthly_orders", "Aylık Siparişler"),
                            ("delayed_orders", "Geciken Siparişler"),
                            ("month_comparison", "Önceki Aya Göre Bu Ay"),
                            ("pending_tickets", "Bekleyen Talepler"),
                            ("new_quotes", "Yeni Teklifler"),
                            ("top_suppliers", "En İyi Tedarikçiler"),
                            ("top_customers", "En İyi Müşteriler"),
                            ("recent_feedback", "Son Değerlendirmeler"),
                            ("order_status", "Sipariş Durum Özeti"),
                            ("revenue_chart", "Gelir Grafiği"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "organization", "is_visible"],
                        name="core_userda_user_id_dbdea7_idx",
                    )
                ],
                "unique_together": {("user", "organization", "widget_type")},
            },
        ),
    ]
