# Generated by Django 4.2.24 on 2025-11-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_membership_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='Gönderen email adresi', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP sunucu adresi (örn: smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP şifre / App Password', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP kullanıcı adı / email', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_port',
            field=models.IntegerField(blank=True, help_text='SMTP port (örn: 587 veya 465)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='SSL kullan (port 465 için)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='TLS kullan (port 587 için)'),
        ),
    ]
