# Generated by Django 4.2.24 on 2025-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_organization_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Kullanıcıya özel sayfa yetkileri'),
        ),
    ]
